<?php
/**
 * SubscriptionPlanItemResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  DocuSign\Admin
 * @author   Swagger Codegen team <apihelp@docusign.com>
 * @license  The Docusign PHP Client SDK is licensed under the MIT License.
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Docusign Admin API
 *
 * An API for an organization administrator to manage organizations, accounts and users
 *
 * OpenAPI spec version: v2.1
 * Contact: devcenter@docusign.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.21
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace DocuSign\Admin\Model;

use \ArrayAccess;
use DocuSign\Admin\ObjectSerializer;

/**
 * SubscriptionPlanItemResponse Class Doc Comment
 *
 * @category    Class
 * @package     DocuSign\Admin
 * @author      Swagger Codegen team <apihelp@docusign.com>
 * @license     The Docusign PHP Client SDK is licensed under the MIT License.
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SubscriptionPlanItemResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SubscriptionPlanItemResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'plan_item_id' => '?string',
        'plan_item_name' => '?string',
        'plan_item_description' => '?string',
        'plan_item_internal_id' => '?string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'plan_item_id' => 'uuid',
        'plan_item_name' => null,
        'plan_item_description' => null,
        'plan_item_internal_id' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'plan_item_id' => 'plan_item_id',
        'plan_item_name' => 'plan_item_name',
        'plan_item_description' => 'plan_item_description',
        'plan_item_internal_id' => 'plan_item_internal_id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'plan_item_id' => 'setPlanItemId',
        'plan_item_name' => 'setPlanItemName',
        'plan_item_description' => 'setPlanItemDescription',
        'plan_item_internal_id' => 'setPlanItemInternalId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'plan_item_id' => 'getPlanItemId',
        'plan_item_name' => 'getPlanItemName',
        'plan_item_description' => 'getPlanItemDescription',
        'plan_item_internal_id' => 'getPlanItemInternalId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['plan_item_id'] = isset($data['plan_item_id']) ? $data['plan_item_id'] : null;
        $this->container['plan_item_name'] = isset($data['plan_item_name']) ? $data['plan_item_name'] : null;
        $this->container['plan_item_description'] = isset($data['plan_item_description']) ? $data['plan_item_description'] : null;
        $this->container['plan_item_internal_id'] = isset($data['plan_item_internal_id']) ? $data['plan_item_internal_id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets plan_item_id
     *
     * @return ?string
     */
    public function getPlanItemId()
    {
        return $this->container['plan_item_id'];
    }

    /**
     * Sets plan_item_id
     *
     * @param ?string $plan_item_id plan_item_id
     *
     * @return $this
     */
    public function setPlanItemId($plan_item_id)
    {
        $this->container['plan_item_id'] = $plan_item_id;

        return $this;
    }

    /**
     * Gets plan_item_name
     *
     * @return ?string
     */
    public function getPlanItemName()
    {
        return $this->container['plan_item_name'];
    }

    /**
     * Sets plan_item_name
     *
     * @param ?string $plan_item_name plan_item_name
     *
     * @return $this
     */
    public function setPlanItemName($plan_item_name)
    {
        $this->container['plan_item_name'] = $plan_item_name;

        return $this;
    }

    /**
     * Gets plan_item_description
     *
     * @return ?string
     */
    public function getPlanItemDescription()
    {
        return $this->container['plan_item_description'];
    }

    /**
     * Sets plan_item_description
     *
     * @param ?string $plan_item_description plan_item_description
     *
     * @return $this
     */
    public function setPlanItemDescription($plan_item_description)
    {
        $this->container['plan_item_description'] = $plan_item_description;

        return $this;
    }

    /**
     * Gets plan_item_internal_id
     *
     * @return ?string
     */
    public function getPlanItemInternalId()
    {
        return $this->container['plan_item_internal_id'];
    }

    /**
     * Sets plan_item_internal_id
     *
     * @param ?string $plan_item_internal_id plan_item_internal_id
     *
     * @return $this
     */
    public function setPlanItemInternalId($plan_item_internal_id)
    {
        $this->container['plan_item_internal_id'] = $plan_item_internal_id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}

